{% set name = "opentelemac" %}
{% set version = "v9.0.0" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/-/archive/{{ version }}/telemac-mascaret-{{ version }}.tar.gz
    folder: opentelemac
    sha256: 3797b9573a78e610e99c89507446783905d10f450500cfedc64a46f9dd21e5f8
    patches:
      - patches/adapt-systel-debian-to-conda.patch  # [linux]

build:
  number: {{ build }}
  skip: true  # [not linux]
  script_env:
    - TELEMAC_VERSION={{ version }}  # [not linux]
  missing_dso_whitelist:
    - '*/libc.so.6'
    - '*/libpthread.so.0'
    - '*/libm.so.6'
  ignore_run_exports_from:
    # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
    # compiler('c'), and conda keeps that despite ignoring the cxx run-exports
    - {{ compiler('cxx') }}
  ignore_run_exports:
    - numpy
  rpaths:
    # WARNING: All plateforms should share same config name!
    - opentelemac/builds/gnu.shared/lib

requirements:
  build:
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - sed
  host:
    - openmpi
    - meson
    - metis
    - python
    - numpy <2.0dev0
    - setuptools <65  # [py<312]
  run:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openmpi
    - python
    - meson
    - numpy <2.0dev0
    - metis
    - matplotlib-base
    - scipy
    - mpi4py
    - setuptools <65  # [py<312]

test:
  commands:
    - config.py

about:
  home: http://www.opentelemac.org/
  license: GPL-3.0-or-later
  license_file: opentelemac/LICENSE.txt
  summary: openTelemac
  description: |
    The TELEMAC-MASCARET system is an integrated suite of solvers for use in the
    field of free-surface flow.
  doc_url: http://wiki.opentelemac.org/doku.php?id=documentation_{{ version }}
  dev_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/

extra:
  recipe-maintainers:
    - nicogodet
    - tomsail
