{% set name = "opentelemac" %}
{% set version = "v8p5r0" %}
{% set build = 2 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/-/archive/{{ version }}/telemac-mascaret-{{ version }}.tar.gz
    folder: opentelemac
    sha256: 2beb9793fb83d17de31b17f001f985fc30702c151e2ced614f5e0117e8e34aa0

build:
  number: {{ build }}
  skip: true  # [not linux]
  script_env:
    - TELEMAC_VERSION={{ version }}
  missing_dso_whitelist:
    - '*/libc.so.6'
    - '*/libpthread.so.0'
    - '*/libm.so.6'
  ignore_run_exports:
    - libstdcxx-ng
    - numpy
  rpaths:
    - opentelemac/builds/gnu.dynamic/lib

requirements:
  build:
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]
  host:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - openmpi
    - python
    - metis
    - numpy
    - sed
  run:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openmpi
    - python
    - numpy
    - metis
    - matplotlib-base
    - scipy
    - mpi4py
    - notebook
    - ipympl

test:
  commands:
    - config.py

about:
  home: http://www.opentelemac.org/
  license: GPL-3.0-or-later
  license_file: opentelemac/LICENSE.txt
  summary: openTelemac
  description: |
    The TELEMAC-MASCARET system is an integrated suite of solvers for use in the
    field of free-surface flow.
  doc_url: http://wiki.opentelemac.org/doku.php?id=documentation_{{ version }}
  dev_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/

extra:
  recipe-maintainers:
    - nicogodet
    - tomsail
